DM-27811: Remove deprecated filterLabel component.
lsst/obs_base pull request #434
Opened 2022-10-05 20:15 UTC by erykoff

## Checklist

- [ ] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`

2022-10-05 21:49 UTC, kfindeisen requested changes
Unfortunately, you missed `exposureAssembler.py`, which needs to be kept in sync with the non-disassembled code. The way the tests are set up means that removing `filterLabel` from `test_butlerFits` prevents the mismatch from being tested. :disappointed:

2022-10-05 21:49 UTC, kfindeisen commented on doc/changes/DM-27811.removal.md
> +Remove deprecated filterLabel exposure component access.
I would argue for merging these two commits, as they're not self-contained -- if 2e0ca30 were removed, this log would be incorrect; if 4877849 were removed, the cleanup would be incomplete.

2022-10-06 01:01 UTC, erykoff commented
Thanks for catching that!  I was relying too much on todos and not enough on grep.  Anyway, everything is removed now.

2022-10-06 17:03 UTC, kfindeisen approved these changes
Looks good!

2022-10-06 18:53 UTC, merged